server:
 port: 9091

 
logging:
 level:
  org:
   springframework:
    data:
     mongodb:
      core:
       MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: bank-db
      port: 27017
      host: localhost