logging:
 level:
  org:
   springframework:
    data:
     mongodb:
      core:
       MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: bank-db
      port: 27017
      host: localhost
  kafka:
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092      