version: '3.1'
services:
  bank-transfer-api:
    container_name: bank-transfer-api
    build:
      context: bank-transfer-api
      dockerfile: Dockerfile
    image: bank-transfer-api:latest
    ports:
      - 9090:9090
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - bank-network
  transactions-api:
    container_name: transactions-api
    image: transactions-api:latest
    build:
      context: transactions-api
      dockerfile: Dockerfile
    image: transactions-api:latest
    ports:
      - 9091:9091
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongodb:27017/bank-db?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: group-1
    depends_on:
      - mongodb
      - kafka
    networks:
      - bank-network
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - bank-network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "transactions:1:3"
    depends_on:
      - zookeeper
    networks:
      - bank-network  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - bank-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - bank-network  
networks:
  bank-network:
    driver: bridge     
 
